### ISSUE TITLE
Invalid argument: '*.cnf'

### ISSUE THREAD

**Issue by shivamjgandhi** [andertavares/mlbf#7]
Hello,

I try to run the following command: `python mlbf/main.py *.cnf --output=out.csv` and then get the following error:
```
Traceback (most recent call last):
  File "mlbf/mlbf/main.py", line 119, in <module>
    fire.Fire(main)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "mlbf/mlbf/main.py", line 37, in main
    data_x, data_y = dataset.get_dataset(cnf, solver)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\dataset.py", line 74, in get_dataset
    return generate_dataset(path, solver, num_positives, num_negatives, save_dataset, overwrite)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\dataset.py", line 127, in generate_dataset
    positives = positive_sampler.sample(cnf, num_positives)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\positives.py", line 97, in sample
    f = CNF(cnf_file)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\formula.py", line 420, in __init__
    self.from_file(from_file, comment_lead, compressed_with='use_ext')
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\formula.py", line 463, in from_file
    with FileObject(fname, mode='r', compression=compressed_with) as fobj:
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\_fileio.py", line 108, in __init__
    self.open(name, mode=mode, compression=compression)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\_fileio.py", line 123, in open
    self.fp = open(name, mode)
OSError: [Errno 22] Invalid argument: '*.cnf'
```
I'm not entirely sure what to replace '*.cnf' with, or if I need to make sure some libraries are installed. Please let me know what I can do to fix this issue. Thanks!

**Comment by marcionicolau** [comment]
Hi Shivam,I think you must inform a path pointing to a directory with cnf files instead of a wildcard. Marcio Nicolau PhD Candidate in Computer Science marcio.nicolau@ufrgs.brEm 23 de jan de 2021 17:18, Shivam Gandhi <notifications@github.com> escreveu:
Hello,
I try to run the following command: python mlbf/main.py *.cnf --output=out.csv and then get the following error:
Traceback (most recent call last):
  File "mlbf/mlbf/main.py", line 119, in <module>
    fire.Fire(main)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "mlbf/mlbf/main.py", line 37, in main
    data_x, data_y = dataset.get_dataset(cnf, solver)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\dataset.py", line 74, in get_dataset
    return generate_dataset(path, solver, num_positives, num_negatives, save_dataset, overwrite)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\dataset.py", line 127, in generate_dataset
    positives = positive_sampler.sample(cnf, num_positives)
  File "C:\Users\test\Documents\Statmech-ML\mlbf\mlbf\positives.py", line 97, in sample
    f = CNF(cnf_file)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\formula.py", line 420, in __init__
    self.from_file(from_file, comment_lead, compressed_with='use_ext')
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\formula.py", line 463, in from_file
    with FileObject(fname, mode='r', compression=compressed_with) as fobj:
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\_fileio.py", line 108, in __init__
    self.open(name, mode=mode, compression=compression)
  File "C:\Users\test\anaconda3\envs\Statmech-ML\lib\site-packages\pysat\_fileio.py", line 123, in open
    self.fp = open(name, mode)
OSError: [Errno 22] Invalid argument: '*.cnf'

I'm not entirely sure what to replace '*.cnf' with, or if I need to make sure some libraries are installed. Please let me know what I can do to fix this issue. Thanks!

**Comment by andertavares** [comment]
Hi Shivam, the '*.cnf' must be replaced by the location of your .cnf files (each .cnf should contain a formula in CNF DIMACS format).

Suppose you have 100 .cnf files in directory `/home/user`. Then you run the program with: `python mlbf/main.py /home/user/*.cnf --output=out.csv`.

**Comment by shivamjgandhi** [comment]
Gotcha, I see. Is there any way I can get some .cnf files? I tried to run the script with mlbf/instances/bw_large.d.cnf but it said that there are 0 instances.

**Comment by andertavares** [comment]
Hi Shivam,

You can run on SATLIB instances:
https://www.cs.ubc.ca/~hoos/SATLIB/benchm.html

Try, for example, uf100-430 and flat30-60 and let us know if you find any
problems.


Em sex., 29 de jan. de 2021 às 22:20, Shivam Gandhi <
notifications@github.com> escreveu:

**Comment by shivamjgandhi** [comment]
Running `python mlbf/mlbf/main.py cnf/uf100/uf100-01.cnf --output=out.csv` and getting the following error:

```
Generating positive instances.
Calling unigen.
Attempting to compute startIteration with sharpSAT
.\doalarm -t real 300 ./sharpSAT -q C:\Users\test\Documents\Statmech-ML\cnf\uf100\uf100-01.cnf > /tmp/unigen\positives\C:\Users\test\Documents\Statmech-ML\cnf\uf100\uf100-01_0.count
The filename, directory name, or volume label syntax is incorrect.
Traceback (most recent call last):
  File "UniGen2.py", line 234, in <module>
    main()
  File "UniGen2.py", line 177, in main
    f = open(countLogFile, 'r')
OSError: [Errno 22] Invalid argument: '/tmp/unigen\\positives\\C:\\Users\\test\\Documents\\Statmech-ML\\cnf\\uf100\\uf100-01_0.count'
WARNING! there has been some error with unigen's execution. Please check the output above.
Samples file /tmp/unigen\positives\uf100-01_0.txt does not exist. Returning empty.
Sampled 0 unique positive instances
WARNING: No positives samples for cnf/uf100/uf100-01.cnf. Returning empty dataset...
cnf/uf100/uf100-01.cnf has 0 instances, which is less than 100 (too few to learn). Aborting.
```

It seems to be an issue with something called unigen. Any idea on how I can fix this? I think the cnf files are correct. Unigen is making it so that there is no temporary file that the script needs to create the appropriate dataset.

**Comment by andertavares** [comment]
Hi Shivam, now I see that you are using Windows and there are two problems with this:
1) The directory used by unigen is hardcoded for Linux: `/tmp/unigen`. This is fixable. You can change it in `mlbf/positives.py` in the constructor of class `UnigenSampler`
2) The unigen binary that we are using was compiled in Linux. Probably, it won't work. If you want to try to compile it for windows, the code of Unigen2 is at: https://bitbucket.org/kuldeepmeel/unigen/ (you'll probably need to clone and "downgrade" a few commits, as they moved to the new repository for Unigen3 at: https://github.com/meelgroup/unigen. 

The easiest way to work around this is to use a GNU/Linux system. Sorry for assuming this as default and not adding to the documentation.
